"""
MissionMind Timeline Engine
============================
Generates deterministic timelines from timestamped mission records.

The timeline is NOT generated by the LLM.
It is built deterministically from actual records.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Optional

from app import db
from app.schemas import TimelineEvent, Severity

logger = logging.getLogger("missionmind.timeline")


def generate_timeline(
    record_ids: Optional[list[str]] = None,
    subsystem: Optional[str] = None,
    time_start: Optional[str] = None,
    time_end: Optional[str] = None,
    anomaly_id: Optional[str] = None,
) -> list[TimelineEvent]:
    """
    Generate a deterministic timeline from mission records.

    The timeline respects actual timestamps and never invents events.

    Args:
        record_ids: Specific record IDs to include
        subsystem: Filter by subsystem
        time_start: Start of time window
        time_end: End of time window
        anomaly_id: Associated anomaly ID

    Returns:
        List of TimelineEvent sorted by timestamp
    """
    records: list[dict[str, Any]] = []

    # If specific record IDs are provided, use those
    if record_ids:
        records_map = db.get_records_by_ids(record_ids)
        records = list(records_map.values())
    else:
        # Otherwise, search by filters
        records = db.search_records_sql(
            subsystem=subsystem,
            time_start=time_start,
            time_end=time_end,
            limit=100,
        )

    if not records:
        return []

    # Convert records to timeline events
    events: list[TimelineEvent] = []
    for record in records:
        event = _record_to_timeline_event(record)
        if event:
            events.append(event)

    # Sort by timestamp (deterministic)
    events.sort(key=lambda e: e.timestamp)

    logger.info("Generated timeline with %d events", len(events))
    return events


def generate_timeline_for_records(
    records: list[dict[str, Any]],
) -> list[TimelineEvent]:
    """
    Generate a timeline from a pre-fetched list of records.
    Used when records are already retrieved by the AI pipeline.
    """
    events: list[TimelineEvent] = []
    for record in records:
        event = _record_to_timeline_event(record)
        if event:
            events.append(event)

    events.sort(key=lambda e: e.timestamp)
    return events


def _record_to_timeline_event(record: dict[str, Any]) -> Optional[TimelineEvent]:
    """Convert a mission record into a timeline event."""
    try:
        # Parse timestamp
        ts_str = record.get("timestamp", "")
        if isinstance(ts_str, str):
            # Handle multiple timestamp formats
            for fmt in [
                "%Y-%m-%dT%H:%M:%S",
                "%Y-%m-%dT%H:%M:%S.%f",
                "%Y-%m-%d %H:%M:%S",
                "%Y-%m-%d %H:%M:%S.%f",
                "%Y-%m-%dT%H:%M:%SZ",
                "%Y-%m-%dT%H:%M:%S%z",
                "%Y-%m-%d %H:%M:%S %Z",
            ]:
                try:
                    timestamp = datetime.strptime(ts_str.replace(" UTC", ""), fmt)
                    break
                except ValueError:
                    continue
            else:
                # Last resort: try direct parsing
                timestamp = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        elif isinstance(ts_str, datetime):
            timestamp = ts_str
        else:
            return None

        # Build description from record
        description = _build_event_description(record)

        # Map severity
        severity_str = record.get("severity", "info").lower()
        severity_map = {
            "info": Severity.INFO,
            "warning": Severity.WARNING,
            "critical": Severity.CRITICAL,
        }
        severity = severity_map.get(severity_str, Severity.INFO)

        return TimelineEvent(
            timestamp=timestamp,
            record_id=record.get("id", "UNKNOWN"),
            subsystem=record.get("subsystem", "UNKNOWN"),
            event_type=record.get("record_type", "unknown"),
            description=description,
            severity=severity,
        )

    except Exception as e:
        logger.warning("Could not create timeline event: %s", e)
        return None


def _build_event_description(record: dict[str, Any]) -> str:
    """Build a concise description for a timeline event."""
    text = record.get("text", "")
    params = record.get("parameters", {})

    # If text is short enough, use it directly
    if len(text) <= 120:
        return text

    # Otherwise, summarize from parameters
    if isinstance(params, dict) and params:
        parts = []
        for key, value in list(params.items())[:3]:
            parts.append(f"{key}={value}")
        return f"{record.get('subsystem', 'UNKNOWN')}: {', '.join(parts)}"

    # Truncate long text
    return text[:117] + "..."
